### ISSUE TITLE
ImportError: cannot import name backend

### ISSUE THREAD

**Issue by ssoulhi** [delftrobotics/keras-retinanet#50]
Hi,
Got ImportError when trying to import keras_retinanet:

Code:

%matplotlib inline
%load_ext autoreload
%autoreload 2

#import keras
import keras_retinanet

import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
import time

import tensorflow as tf

def get_session():
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    return tf.Session(config=config)

# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
keras.backend.tensorflow_backend.set_session(get_session())

Error:

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-170a719f6276> in <module>()
      5 
      6 #import keras
----> 7 import keras_retinanet
      8 
      9 

build/bdist.linux-x86_64/egg/keras_retinanet/__init__.py in <module>()
----> 1 from . import backend
      2 from . import initializers
      3 from . import layers
      4 from . import losses
      5 from . import models

ImportError: cannot import name backend

**Comment by anex004** [comment]
Same issue "ImportError: cannot import name backend", along with many other.

**Comment by hgaiser** [comment]
Can you tell me more about the system / environment you're running this on?

**Comment by anex004** [comment]
Thanks for getting back.

I am using Ubuntu 14.04, Python 2.7, Keras 2 with Tensorflow as backend,  and opencv 3.3. 

Also, its seems like it is looking for coco api, even if I am training for Pascal 2007.

Please let me know if you need any further details.

**Comment by anex004** [comment]
Also, what version of tensorflow are you using? Thank you

**Comment by hgaiser** [comment]
I'm running tensorflow `1.4.0rc0` but I don't think that is related. It's strange that you get this error. I tried to reproduce it using python2 but it didn't happen for me. Could you try with python3 to see if that helps? Or could you try replacing the import lines from:
```
from . import backend
```
to:
```
import keras_retinanet.backend as backend
```
(and probably the other imports too)

**Comment by anex004** [comment]
Hi Hans,

Thanks for your suggestion, appreciate it. I will try with the updated options. Let's see how does it go.

**Comment by anex004** [comment]
Solved! 

I tried with a newer version of tensorflow ( v 1.2 ) and it seems to work with this version.  

But I am getting a new error saying:

TypeError: __init__() got an unexpected keyword argument 'freeze_bn'

It has something to do with the legacy code of Keras. Any idea about it?

Let me know if I should open a new thread for this. 

Below is the detailed description:

`
Traceback (most recent call last):
  File "examples/train_pascal.py", line 60, in <module>
    model = create_model(weights=args.weights)
  File "examples/train_pascal.py", line 38, in create_model
    return ResNet50RetinaNet(image, num_classes=20, weights=weights)
  File "/home/anirbanroy/anaconda2/envs/tensorflow_keras/lib/python2.7/site-packages/keras_retinanet/models/resnet.py", line 36, in ResNet50RetinaNet
    resnet = keras_resnet.models.ResNet50(image, include_top=False, freeze_bn=True)
  File "/home/anirbanroy/anaconda2/envs/tensorflow_keras/lib/python2.7/site-packages/keras_resnet/models/_2d.py", line 178, in ResNet50
    return ResNet(inputs, blocks, block=keras_resnet.blocks.bottleneck_2d, include_top=include_top, classes=classes, *args, **kwargs)
  File "/home/anirbanroy/anaconda2/envs/tensorflow_keras/lib/python2.7/site-packages/keras_resnet/models/_2d.py", line 82, in ResNet
    return keras.models.Model(inputs=inputs, outputs=outputs, *args, **kwargs)
  File "/home/anirbanroy/anaconda2/envs/tensorflow_keras/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'freeze_bn'
`

**Comment by hgaiser** [comment]
Check the README.md, you need the master of keras-resnet.

On Nov 10, 2017 21:30, "anex004" <notifications@github.com> wrote:

Solved!

I tried with a newer version of tensorflow ( v 1.2 ) and it seems to work
with this version.

But I am getting a new error saying:

TypeError: *init*() got an unexpected keyword argument 'freeze_bn'

It has something to do with the legacy code of Keras. Any idea about it?

Let me know if I should open a new thread for this.

Below is the detailed description:

Traceback (most recent call last): File "examples/train_pascal.py", line
60, in <module> model = create_model(weights=args.weights) File
"examples/train_pascal.py", line 38, in create_model return
ResNet50RetinaNet(image, num_classes=20, weights=weights) File
"/home/anirbanroy/anaconda2/envs/tensorflow_keras/lib/
python2.7/site-packages/keras_retinanet/models/resnet.py", line 36, in
ResNet50RetinaNet resnet = keras_resnet.models.ResNet50(image,
include_top=False, freeze_bn=True) File "/home/anirbanroy/anaconda2/
envs/tensorflow_keras/lib/python2.7/site-packages/keras_resnet/models/_2d.py",
line 178, in ResNet50 return ResNet(inputs, blocks,
block=keras_resnet.blocks.bottleneck_2d, include_top=include_top,
classes=classes, *args, **kwargs) File "/home/anirbanroy/anaconda2/
envs/tensorflow_keras/lib/python2.7/site-packages/keras_resnet/models/_2d.py",
line 82, in ResNet return keras.models.Model(inputs=inputs,
outputs=outputs, *args, **kwargs) File "/home/anirbanroy/anaconda2/
envs/tensorflow_keras/lib/python2.7/site-packages/keras/legacy/interfaces.py",
line 87, in wrapper return func(*args, **kwargs) TypeError: __init__() got
an unexpected keyword argument 'freeze_bn'

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/delftrobotics/keras-retinanet/issues/50#issuecomment-343578053>,
or mute the thread

**Comment by anex004** [comment]
Yes, I had downloaded and installed the keras-resnet and models from that library can be accessed, for example, the ResNet50 model is invoked fine.

Thank you

**Comment by hgaiser** [comment]
So this issue can be closed ?

**Comment by anex004** [comment]
Hey, I meant to say the I installed the keras-resnet following the link as you mentioned, it can connect to the library but still has the type error!

`TypeError: *init*() got an unexpected keyword argument 'freeze_bn'`

**Comment by hgaiser** [comment]
Ah okay. It sounds like it is still not using master branch then. You can try executing `print(keras_resnet.__file__)` to see where it is installed. Verify that it is indeed the correct one.

**Comment by anex004** [comment]
Hi, finally working! 

Thanks a lot for your constant help! Cant appreciate more :-)
